<a href="https://colab.research.google.com/github/Sayara20/CienciaDatos/blob/main/Arreglos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
a=np.array([1,2,3,4,5])

In [4]:
a

array([1, 2, 3, 4, 5])

In [5]:
type(a)

numpy.ndarray

In [7]:
a.size

5

In [8]:
a.ndim

1

In [10]:
a.shape

(5,)

declarar tipo de arreglos

In [11]:
a=np.array([1,2,3,4,5],dtype=bool)

In [12]:
a.dtype

dtype('bool')

In [14]:
a=np.array([1,2,3,4,5],dtype=str)


In [15]:
a

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [16]:
a=np.array([0,1,2,3,4,5], dtype=bool)

In [17]:
a

array([False,  True,  True,  True,  True,  True])

Declarar arreglos

In [19]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arreglos con salto de incremento como tercer parametro

In [21]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
np.zeros(10,dtype=int).dtype

dtype('int64')

In [25]:
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.random.randint(0,10,50)

array([6, 9, 9, 3, 5, 1, 2, 7, 3, 4, 2, 0, 1, 3, 4, 5, 4, 2, 6, 5, 2, 6,
       6, 4, 6, 5, 3, 0, 8, 3, 5, 1, 0, 4, 4, 8, 0, 3, 9, 5, 3, 9, 8, 7,
       4, 0, 3, 6, 4, 7])